loja_genero:
    resource: "@LojaBundle/Controller/GeneroController.php"
    type:     annotation

base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /base/

loja:
    resource: "@LojaBundle/Controller/"
    type:     annotation
    prefix:   /


    
