<?php

namespace LojaBundle\Repository;

/**
 * JogosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JogosRepository extends \Doctrine\ORM\EntityRepository
{
}
